import React from 'react';
import { X, BookOpen, Database, Calendar, CheckSquare, ShieldCheck } from 'lucide-react';
import { useDashboard } from '../../context/DashboardContext';
import { DATASET_METADATA_MAP, ASEAN_COUNTRIES } from '../../data/datasetMetadata';

export const MethodologyModal: React.FC = () => {
  const { showMethodology, setShowMethodology, language } = useDashboard();

  if (!showMethodology) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs overflow-y-auto">
      <div className="bg-white rounded-2xl max-w-3xl w-full shadow-2xl border border-slate-200 overflow-hidden flex flex-col max-h-[90vh]">
        {/* Header */}
        <div className="px-6 py-4 border-b border-slate-200 bg-slate-50 flex items-center justify-between">
          <div className="flex items-center gap-2.5 text-brand-blue">
            <BookOpen className="w-5 h-5" />
            <h2 className="text-base font-bold tracking-tight text-slate-900">
              {language === 'th' ? 'ระเบียบวิธีวิจัยและคำนิยามข้อมูล (Methodology & Definitions)' : 'Methodology & Data Definitions'}
            </h2>
          </div>
          <button
            onClick={() => setShowMethodology(false)}
            className="p-1 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-200/60 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 overflow-y-auto custom-scrollbar text-xs text-slate-700 space-y-6">
          {/* Section 1: Overview */}
          <section>
            <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2 mb-2">
              <Database className="w-4 h-4 text-brand-blue" />
              {language === 'th' ? '1. ที่มาและขอบเขตของโครงการวิจัย' : '1. Research Scope & Background'}
            </h3>
            <p className="leading-relaxed text-slate-600">
              {language === 'th'
                ? 'โครงการวิจัย "รูปแบบการท่องเที่ยวของนักท่องเที่ยวประชาคมเศรษฐกิจอาเซียน" (Tourist Behavior Patterns of ASEAN Tourists Traveling to Thailand) มุ่งเน้นการวิเคราะห์เชิงประจักษ์เกี่ยวกับพฤติกรรม ลักษณะทางประชากรศาสตร์ การใช้จ่าย ระยะเวลาพำนัก และการสร้างรายได้ของนักท่องเที่ยวจาก 9 ประเทศสมาชิกอาเซียนที่เดินทางเข้าประเทศไทย'
                : 'The research project "Tourist Behavior Patterns of ASEAN Tourists Traveling to Thailand" provides an empirical statistical analysis of demographics, travel arrangements, spending patterns, length of stay, and economic revenue generated by visitors from 9 ASEAN member states.'}
            </p>
          </section>

          {/* Section 2: Countries */}
          <section>
            <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2 mb-2">
              <ShieldCheck className="w-4 h-4 text-brand-blue" />
              {language === 'th' ? '2. ขอบเขตประเทศสมาชิกอาเซียนที่ศึกษา (9 ประเทศ)' : '2. ASEAN Member Countries (9 Nations)'}
            </h3>
            <div className="grid grid-cols-3 gap-2 bg-slate-50 p-3 rounded-lg border border-slate-200">
              {ASEAN_COUNTRIES.map((c, i) => (
                <div key={i} className="text-slate-700 font-medium">
                  {i + 1}. {language === 'th' ? c.th : c.en} <span className="text-[10px] text-slate-400">({c.en})</span>
                </div>
              ))}
            </div>
            <p className="text-[11px] text-slate-500 mt-1 italic">
              {language === 'th'
                ? '*หมายเหตุ: ประเทศไทยเป็นจุดหมายปลายทาง (Destination) จึงไม่ได้จัดอยู่ในกลุ่มตลาดต้นทาง (Origin Market) ในชุดข้อมูลนี้'
                : '*Note: Thailand serves as the host destination and is therefore excluded as an origin market.'}
            </p>
          </section>

          {/* Section 3: Datasets and Year Coverage */}
          <section>
            <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2 mb-2">
              <Calendar className="w-4 h-4 text-brand-blue" />
              {language === 'th' ? '3. ชุดข้อมูลทั้ง 15 ชุด และช่วงปีที่ครอบคลุม' : '3. The 15 Datasets & Year Coverage'}
            </h3>
            <div className="border border-slate-200 rounded-lg overflow-hidden">
              <table className="w-full text-left text-[11px]">
                <thead className="bg-slate-100 text-slate-700 font-semibold">
                  <tr>
                    <th className="p-2">ชุดข้อมูล (Dataset)</th>
                    <th className="p-2">ไฟล์ (Filename)</th>
                    <th className="p-2">ช่วงปี (Years)</th>
                    <th className="p-2">หน่วย (Unit)</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {Object.values(DATASET_METADATA_MAP).map((m, idx) => (
                    <tr key={idx} className="hover:bg-slate-50">
                      <td className="p-2 font-medium text-slate-800">{language === 'th' ? m.titleTh : m.titleEn}</td>
                      <td className="p-2 font-mono text-[10px] text-slate-500">{m.filename}</td>
                      <td className="p-2 text-brand-blue font-semibold">
                        {m.years[0]}–{m.years[m.years.length - 1]}
                      </td>
                      <td className="p-2 text-slate-600">{language === 'th' ? m.unitTh : m.unitEn}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>

          {/* Section 4: Key Definitions */}
          <section>
            <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2 mb-2">
              <CheckSquare className="w-4 h-4 text-brand-blue" />
              {language === 'th' ? '4. คำนิยามและสูตรคำนวณทางสถิติ' : '4. Statistical Formulas & Definitions'}
            </h3>
            <ul className="space-y-2 text-slate-600 leading-relaxed">
              <li>
                <strong className="text-slate-800">ปี พ.ศ. (Buddhist Era Years):</strong>{' '}
                {language === 'th'
                  ? 'ระบบบันทึกปีตามปฏิทินพุทธศักราช (พ.ศ.) ซึ่งแปลงเป็นคริสต์ศักราช (ค.ศ.) ได้โดยการลบด้วย 543'
                  : 'Recorded in Buddhist Era (BE). To convert to AD/CE, subtract 543 (e.g. 2562 BE = 2019 CE).'}
              </li>
              <li>
                <strong className="text-slate-800">Year-over-Year Change (% YoY):</strong>{' '}
                <code className="bg-slate-100 px-1.5 py-0.5 rounded text-brand-blue font-mono">
                  ((Current Year - Previous Year) / Previous Year) × 100
                </code>
              </li>
              <li>
                <strong className="text-slate-800">สัดส่วนร้อยละ (Market Share %):</strong>{' '}
                <code className="bg-slate-100 px-1.5 py-0.5 rounded text-brand-blue font-mono">
                  (Category Value / Total ASEAN Value) × 100
                </code>
              </li>
              <li>
                <strong className="text-slate-800">การเดินทางด้วยตนเอง (FIT):</strong>{' '}
                {language === 'th'
                  ? 'Free Independent Travelers (เดินทางด้วยตนเอง ไม่ผ่านกรุ๊ปทัวร์)'
                  : 'Free Independent Travelers who arrange their own travel and accommodation without package tours.'}
              </li>
              <li>
                <strong className="text-slate-800">ระยะเวลาพำนักเฉลี่ย (Average Length of Stay):</strong>{' '}
                {language === 'th'
                  ? 'ค่าที่แสดงเป็นค่าเฉลี่ยระดับประเทศต่อปีจากแบบสำรวจอย่างเป็นทางการของภาครัฐ ไม่มีการถ่วงน้ำหนักซ้ำซ้อน'
                  : 'Values represent official national survey averages per country/year as reported in source statistics.'}
              </li>
            </ul>
          </section>

          {/* Section 5: Weighted vs Unweighted Averages */}
          <section>
            <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2 mb-2">
              <CheckSquare className="w-4 h-4 text-brand-blue" />
              {language === 'th' ? '5. ค่าเฉลี่ยระดับประเทศ vs ค่าเฉลี่ยถ่วงน้ำหนัก (Weighted vs. Unweighted)' : '5. Country Mean vs. Volume-Weighted Mean'}
            </h3>
            <div className="space-y-3 leading-relaxed text-slate-600">
              <div className="p-3 bg-slate-50 rounded-lg border border-slate-200 space-y-1.5">
                <div className="font-semibold text-slate-800">
                  {language === 'th' ? 'A. ค่าเฉลี่ยระดับประเทศ (Country Mean — Unweighted):' : 'A. Country Mean (Unweighted):'}
                </div>
                <p>
                  {language === 'th'
                    ? 'คำนวณโดยหาค่าเฉลี่ยทางคณิตศาสตร์อย่างง่ายจากค่าสถิติของทั้ง 9 ประเทศ โดยให้ความสำคัญของแต่ละประเทศเท่าเทียมกัน เหมาะสำหรับการเปรียบเทียบเชิงนโยบายระดับประเทศ'
                    : 'Calculated as the unweighted arithmetic mean across all 9 member states, treating each country equally regardless of population or arrival volume.'}
                </p>
                <code className="block bg-white p-2 rounded border border-slate-200 text-brand-blue font-mono text-[10px]">
                  Country Mean = SUM(Country Averages) / Number of Countries
                </code>
              </div>

              <div className="p-3 bg-slate-50 rounded-lg border border-slate-200 space-y-1.5">
                <div className="font-semibold text-slate-800">
                  {language === 'th' ? 'B. ค่าเฉลี่ยถ่วงน้ำหนักตามจำนวนนักท่องเที่ยว (Tourist-Volume Weighted Mean):' : 'B. Tourist-Volume Weighted Mean:'}
                </div>
                <p>
                  {language === 'th'
                    ? 'คำนวณโดยนำจำนวนนักท่องเที่ยวจริงของแต่ละประเทศมาเป็นตัวถ่วงน้ำหนัก ทำให้สะท้อนพฤติกรรมเฉลี่ยของ "นักท่องเที่ยวรายบุคคล" ในภาพรวมอาเซียนอย่างแท้จริง'
                    : 'Weights each country by its tourist arrival volume, capturing the true aggregate experience of an individual ASEAN visitor.'}
                </p>
                <code className="block bg-white p-2 rounded border border-slate-200 text-brand-blue font-mono text-[10px]">
                  Weighted Mean = SUM(Tourist Count × Country Metric) / SUM(Tourist Count)
                </code>
              </div>
            </div>
          </section>

          {/* Section 6: Data Limitations & Policy on Missing Years */}
          <section>
            <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2 mb-2">
              <Database className="w-4 h-4 text-brand-blue" />
              {language === 'th' ? '6. ข้อจำกัดของข้อมูลและการจัดการปีที่ไม่มีข้อมูล (Data Limitations & Missing Data Policy)' : '6. Data Coverage & Missing Data Policy'}
            </h3>
            <p className="leading-relaxed text-slate-600 mb-2">
              {language === 'th'
                ? 'ระบบสถิตินี้รักษาความถูกต้องทางวิชาการโดยไม่สร้างข้อมูลเทียม (No Fabricated Data) และไม่เติมศูนย์แทนที่ข้อมูลที่ไม่มีการจัดเก็บ หากปีที่เลือกอยู่นอกช่วงเวลาที่มีการสำรวจของชุดข้อมูลนั้น ๆ ระบบจะแสดงผลเป็น "ไม่มีข้อมูลสำหรับปีนี้" (No data available) เพื่อป้องกันการตีความผิดพลาด'
                : 'To maintain academic integrity, this system never fabricates data or fills missing survey periods with false zeros. When an indicator is unavailable for a selected year, the system explicitly displays "No data available for this year".'}
            </p>
            <ul className="list-disc list-inside space-y-1 text-[11px] text-slate-600 pl-1">
              <li><strong>Tourist Volume:</strong> 2554–2567 BE (14 years)</li>
              <li><strong>Stay Duration:</strong> 2554–2565 BE (12 years)</li>
              <li><strong>Tourism Revenue:</strong> 2554–2564 BE (11 years)</li>
              <li><strong>Demographics, Behavior, Objectives, Expenses:</strong> 2554–2563 BE (10 years)</li>
              <li><strong>Flight Types & Annual Income:</strong> 2562–2563 BE (2 years)</li>
            </ul>
          </section>
        </div>

        {/* Footer */}
        <div className="px-6 py-3 border-t border-slate-200 bg-slate-50 flex items-center justify-between">
          <span className="text-[11px] text-slate-500 italic">
            {language === 'th' ? 'ข้อมูลสถิติเพื่อการศึกษาวิจัย' : 'Academic Research Dataset'}
          </span>
          <button
            onClick={() => setShowMethodology(false)}
            className="px-4 py-1.5 text-xs font-semibold text-white bg-brand-blue hover:bg-navy-800 rounded-lg transition-colors"
          >
            {language === 'th' ? 'ปิดหน้าต่าง' : 'Close'}
          </button>
        </div>
      </div>
    </div>
  );
};
